CREATE DATABASE FARMACIAHOSPITAL;

CREATE TABLE PACIENTE (

	NRO_DOCUMENTO INT PRIMARY KEY,
	APELLIDO_NOMBRE VARCHAR(100),
	DOMICILIO VARCHAR(100),
	LOCALIDAD VARCHAR(100),
	TELEFONO VARCHAR(20),
	OS VARCHAR(2) DEFAULT 'NO',
	FECHA_NACIMIENTO DATE,
	HC INT(11)
);

CREATE TABLE MEDICAMENTO (
	
	ID_MEDICAMENTO BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_MEDICAMENTO VARCHAR(100)
	
);

CREATE TABLE PACIENTE_MEDICAMENTO (
	
	ID_PACIENTE_MEDICAMENTO BIGINT PRIMARY KEY AUTO_INCREMENT,
	NRO_DOCUMENTO INT,
	ID_MEDICAMENTO BIGINT,
	CANTIDAD INT(4)
	
);